### PR TITLE
Use Promise for asynchronous ping

### PR DESCRIPTION
**Pull request by willpan**
Wrap tcp-ping `ping()` in a Promise and execute pings in parallel using `Promise.all()`.

### CODE REVIEW

**Comment by mda590** [comment]
Dude, thanks for this! Every time I start looking at JS promises, I end up more confused than when I started. Seeing it here makes it look so simple. Will merge and deploy this weekend. Thank you!!

**Comment by pringshia** [comment]
:+1: Most modern browsers support JS promises, but you may want to add a polyfill for the very few that don't:

**Comment by willpan** [comment]
@pringshia The Promise only runs on the backend, no polyfills needed.

**Comment by pringshia** [comment]
Ah I assumed it was client-side code. Yep, all good in that case.

**Pull request merged**
